#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

export TASTY_HIDE_SUCCESSES=True
export TASTY_QUICKCHECK_TESTS=20

executable=${1:-"test-mars"}

ghcid \
  --lint \
  --command="cabal v2-repl $executable" \
  --test="main"
